### ISSUE TITLE
DB doesn't seem to retrieve Glamourer presets anymore.

### ISSUE THREAD

**Issue by Kliuqard** [Limiana/DynamicBridgeStandalone#26]
"IPC method Glamourer.RevertCharacter was not registered yet" is the error that occurs whenever the plugin starts. When investigating, the presets I had assigned in DB were no longer assigned with their Glamourer name (only a red hexadecimal version of its name).

Evidently, Glamourer had an update that "Reworked the API and IPC structure heavily."

**Comment by Limiana** [comment]
Hello! Glamourer and Penumbra functions are unavailable at this moment due to changes to IPC that rendered old methods unusable. I'm currently working on updating to use either new API or other means, but due to absence of documentation from Glamourer/Penumbra side I can not tell any exact dates when it will be back.
In meantime, you can manually install older versions of Glamourer and Penumbra:
https://github.com/Ottermandias/Glamourer/releases/tag/1.2.0.8
https://github.com/xivdev/Penumbra/releases/tag/1.0.1.0

**Comment by Limiana** [comment]
Should be good with 1.0.5.9
