### ISSUE TITLE
Support for Moodles

### ISSUE THREAD

**Issue by Lumura** [Limiana/DynamicBridgeStandalone#5]
If possible, could integration be supported for the Moodles plugin?

**Comment by Lumura** [comment]
Thank you very much!

**Comment by Solandus** [comment]
Maybe we can add in this also "if specific person is close" or things like "amount of people close" as new conditions?

**Comment by Limiana** [comment]
> Maybe we can add in this also "if specific person is close" or things like "amount of people close" as new conditions?

this could be added technically as a rule condition but I don't know, sounds a bit creepy to me, I'll need @AsunaTsuki 's opinion

**Comment by Solandus** [comment]
Well I just wanted to get a happy moodle when my ingame mate is close and a grumpy one when not. q.q Nothing creepy in here! *sad noises*

**Comment by AsunaTsuki** [comment]
This may potentially cause a performance impact to your game, the way it would work is instead of just checking fixed states of the game it would be required to check constantly who is around you at any given time. We will look into it more in depth for sure and can see what we can do. It will probably be disabled by default with an option to turn it on for those wanting to use that feature.
